### ISSUE TITLE
JsonReaderException issue

### ISSUE THREAD

**Issue by nedimjahic** [InstaSharp/InstaSharp#73]
Hello,

I have been experimenting with the instasharp library for one of my projects and I have encountered a peculiar issue at the following line:

<code>var response = await tagEndpoint.Recent(topic.hashtag);</code>

With topic.hashtag value being 'brannff'.

Exception:

<b>Unexpected character encountered while parsing value: <. Path '', line 0, position 0.</b>

Stacktrace:

<pre>at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.ReadInternal()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at InstaSharp.Extensions.HttpClientExtensions.<ExecuteAsync>d__0`1.MoveNext()</pre>

Has anyone had a similar issue? I have read the other Newtonsoft issue posted here, but haven't found anything that would help me resolve my problem.

A second JsonReaderException occurs when replacing the problematic line with:

<code>var response = await tagEndpoint.Recent(topic.hashtag, null, null, 50);</code>

Exception:

<b>Could not convert string to integer: 2162994057. Path 'data[0].caption.from.id', line 1, position 1979.</b>

Any help is appreciated.

Thank you

**Comment by fujiy** [comment]
https://github.com/InstaSharp/InstaSharp/issues/71
